Update io.github.uowuo.abaddon.yml
configure: error: Package requirements (sigc++-2.0 >= 2.0.0 glib-2.0 >= 2.6.0 gobject-2.0 >= 2.6.0 gmodule-2.0 >= 2.6.0) were not met.
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively you may set the GLIBMM_CFLAGS and GLIBMM_LIBS environment variables
to avoid the need to call pkg-config.  See the pkg-config man page for
more details.
Error: module glibmm: Child process exited with code 1